### PR TITLE
 chore: initial typescript migration with unit and integration tests 

### PR DESCRIPTION
**Pull request by muenchhausen**
An initial proposal for TypeScript, unit- and integration testing support.
Integration tests run against BIMserver in a docker container on travis-ci.

Integration tests can be found currently here
https://travis-ci.org/muenchhausen/BIMserver-JavaScript-API

Your feedback is welcome!

### CODE REVIEW

**Review by rubendel — COMMENTED** [review]
Sorry but I don't feel comfortable merging this into master and basically changing the language of the API from JavaScript to TypeScript. It will brake all sort of things, for example local development since browsers don't understand TypeScript (last time I checked). I can imagine this to be a welcome branch to be used by people who are already using TypeScript in their projects. Would you mind putting it into a branch?

**Comment by muenchhausen** [comment]
I fully aggree. I have no access rights to create a branch in this repo. Can you create a branch where I create a pull request to?

**Comment by rubendel** [comment]
Sure, created "typescript"

**Comment by muenchhausen** [comment]
Pull Request is done for branch typescript.

**Pull request closed without merging**
